name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x "PixelPerfect Android/gradlew"
      
    - name: Build Android APK
      run: |
        cd "PixelPerfect Android"
        ./gradlew assembleDebug
        
    - name: Build Android AAB (Release)
      run: |
        cd "PixelPerfect Android"
        ./gradlew bundleRelease
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: PixelPerfect-Android-Debug
        path: PixelPerfect Android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: PixelPerfect-Android-Release
        path: PixelPerfect Android/app/build/outputs/bundle/release/app-release.aab
        
    - name: Upload Debug APK to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: PixelPerfect Android/app/build/outputs/apk/debug/app-debug.apk
        asset_name: PixelPerfect-Android.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Upload Release AAB to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: PixelPerfect Android/app/build/outputs/bundle/release/app-release.aab
        asset_name: PixelPerfect-Android.aab
        asset_content_type: application/octet-stream
